"""add progress to analysis_tasks

Revision ID: 892221e48838
Revises: 13bb6e573f11
Create Date: 2026-08-29 11:15:22.122683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892221e48838'
down_revision: Union[str, Sequence[str], None] = '13bb6e573f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'progress')
    # ### end Alembic commands ###
