"""add created_at to analysis_tasks

Revision ID: e63bf91edba4
Revises: a8f3d2b7c91e
Create Date: 2026-08-29 10:01:35.334050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63bf91edba4'
down_revision: Union[str, Sequence[str], None] = 'a8f3d2b7c91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'created_at')
    # ### end Alembic commands ###
